import { readBlocks, readOverview } from "@/server/modules/blocks";
import { protocolText } from "@/server/modules/protocol-text";

/**
 * Replication Recipe registration mapping (ADR-0005 amendment 3 / ADR-0039).
 * Response keys verified LIVE against api.osf.io on 2026-06-12 — schema
 * "Replication Recipe (Brandt et al., 2014): Pre-Registration"
 * (id 64b14a08d639e5000d2013a5, version 2); every field is optional there, so
 * we file what we hold and the researcher completes the rest on OSF.
 */
export const RECIPE_SCHEMA_NAME = "Replication Recipe (Brandt et al., 2014): Pre-Registration";

/**
 * Standard AI non-determinism disclosure (ADR-0061 amendment 1). Auto-appended
 * to the registration body when the study contains an AI conversation block, so
 * the registered plan states that the AI step isn't reproducible like a fixed
 * questionnaire. Returns undefined when there's no AI block.
 */
export function aiNonDeterminismDisclosure(snapshot: unknown): string | undefined {
  const n = readBlocks(snapshot).filter((b) => b.key === "ai-chat").length;
  if (n === 0) return undefined;
  return (
    `AI CONVERSATION — NON-DETERMINISM DISCLOSURE\n` +
    `This study includes ${n} AI conversation step${n === 1 ? "" : "s"} in which the participant ` +
    `talks with a large language model given a researcher-defined role and context. The AI's ` +
    `wording varies between participants, so this step is not reproducible in the way a fixed ` +
    `questionnaire is. The plan fixes the AI's role, context, model, and turn limit; the record ` +
    `for each participant is the saved transcript itself, not a predetermined script.`
  );
}

/**
 * Human-readable design for the default Open-Ended OSF summary (audit step 3):
 * abstract + numbered hypotheses + the clean protocol, so OSF shows real app
 * content above the machine JSON. Returns undefined when there's nothing to say.
 */
export function buildOpenEndedBody(snapshot: unknown): string | undefined {
  const ov = readOverview(snapshot);
  const parts: string[] = [];
  if (ov.abstract.trim()) parts.push(`ABSTRACT\n${ov.abstract.trim()}`);
  const hyps = ov.hypotheses.filter((h) => h.trim());
  if (hyps.length) parts.push(`HYPOTHESES\n${hyps.map((h, i) => `${i + 1}. ${h.trim()}`).join("\n")}`);
  const protocol = protocolText(snapshot);
  if (protocol.length) parts.push(`PROTOCOL\n${protocol.join("\n")}`);
  const ai = aiNonDeterminismDisclosure(snapshot);
  if (ai) parts.push(ai);
  return parts.length ? parts.join("\n\n") : undefined;
}

const KEYS = {
  description: "77-2",
  originalStudy: "77-12",
  sampleSizeTarget: "77-33",
  differences: "77-73",
  analysisPlan: "77-80",
} as const;

function section(snapshot: unknown, id: string): string {
  return (
    readOverview(snapshot)
      .sections.find((s) => s.id === id)
      ?.contentMd.trim() ?? ""
  );
}

export function buildRecipeResponses(opts: {
  snapshot: unknown;
  sourceTitle?: string | null;
  sourceAuthor?: string | null;
  amendmentHeader?: string;
}): Record<string, string> {
  const { snapshot, sourceTitle, sourceAuthor, amendmentHeader } = opts;
  const overview = readOverview(snapshot);
  const out: Record<string, string> = {};

  const target = section(snapshot, "recipe-target-effect");
  const protocol = protocolText(snapshot).join("\n");
  out[KEYS.description] = [
    amendmentHeader,
    target,
    overview.abstract.trim(),
    "--- Full protocol (auto-generated by My Research Lab) ---",
    protocol,
  ]
    .filter(Boolean)
    .join("\n\n");

  if (sourceTitle) {
    out[KEYS.originalStudy] = `${sourceTitle}${sourceAuthor ? ` (${sourceAuthor})` : ""}`;
  }

  const planned = section(snapshot, "recipe-planned-sample");
  if (planned) out[KEYS.sampleSizeTarget] = planned.slice(0, 1000);

  // Per-block rationales + the researcher's differences section.
  const notes = readBlocks(snapshot)
    .filter((b) => typeof b.divergenceNote === "string" && b.divergenceNote.trim())
    .map((b) => `- ${(typeof b.title === "string" && b.title.trim()) || b.key}: ${b.divergenceNote!.trim()}`);
  const diffSection = section(snapshot, "recipe-differences");
  const differences = [diffSection, ...notes].filter(Boolean).join("\n");
  if (differences) out[KEYS.differences] = differences;

  const analysis = overview.sections.find((s) => /analysis/i.test(s.heading))?.contentMd.trim();
  if (analysis) out[KEYS.analysisPlan] = analysis;

  return out;
}
